### ISSUE TITLE
MIDI play-out to UDP

### ISSUE THREAD

**Issue by szk2s** [szk2s/spectral-mpe-editor#15]

**Comment by yuichkun** [comment]
To be clear: You mean OSC, right?

As for the format of the OSC paths, to keep the flexibility for the future updates, I suggest creating subsidiary paths to `midi` because sometimes you may want to add extra features that acts **globally**.
e.g.: `midi/instances/${ch} 144 60 127`
Thus the example above would only pass the message to the specified instance.

**Comment by yuichkun** [comment]
However, I still don't exactly have the clear vision of the entire flow, 
so it would be **very helpful**, (not only for me but for the team), if you could provide us a diagram of the desired entire process.

**Comment by szk2s** [comment]
Okay, I made it.  
Can I hear your further opinion [here](https://docs.google.com/presentation/d/1hBVoKap9BzySnbk6YXmtOlmCST_tbZ9gZ1EWNMNljwI/edit?usp=sharing)?
